### ISSUE TITLE
Release with Rails 7.1+ support 

### ISSUE THREAD

**Issue by mpvosseller** [gregschmit/recurring_select#168]
Can you release a version with support for Rails 7.1. The latest commit `5dd3177` appears to work for me.

Background:

After upgrading to Rails 7.1 I got the below error when using the `f.select_recurring` form helper:
```
undefined method `options_for_select' for #<RecurringSelectHelper::RecurringSelectTag
``

After debugging it seems the problem is that `ActionView::Helpers::FormOptionsHelper` is not included in `RecurringSelectHelper::RecurringSelectTag` for some reason.

I tested the latest commit on `main` (`5dd3177`) and that seems to work. I assume something in or after  https://github.com/gregschmit/recurring_select/pull/166 fixed it.

Thanks!

**Comment by joshRpowell** [comment]
@gregschmit given Rails 7.2 was released last week, can we tag and release the 7.1 support? 

Would be glad to assist, if needed

Thanks for all your work on this helpful Gem!

**Comment by adamavenord** [comment]
I just updated gem to fix this issue.
It works for Rails 7.1+
You can find that in [here](https://github.com/adamavenord/recurring_select).

**Comment by gregschmit** [comment]
There was a major refactoring merged so I pushed out a new gem version `4.0.0.rc1` so if there are any fixes that need to happen, they can be released on `4.0.0`: https://rubygems.org/gems/recurring_select/versions/4.0.0.rc1

Thank you everyone for bugging me about this.

**Comment by msxavi** [comment]
`4.0.0.rc1` seems to be working on Rails 7.1 so far.

**Comment by graham-jobber** [comment]
I'm (belatedly) updating from Rails 7.0->7.1. I see that 4.0.0 is still tagged as `rc`. Haven't seen any issues with it since updating. Can this be updated to a full release? @gregschmit

**Comment by crpahl** [comment]
@gregschmit Echoing @graham-jobber, could we please make this a full release?
